// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBM8wsjuHwQMRYue8fb0sg_G9ghbGb1Q8',
    appId: '1:742349350458:web:9c4fd3c45d98c3cb173703',
    messagingSenderId: '742349350458',
    projectId: 'learnstorm-63eb7',
    authDomain: 'learnstorm-63eb7.firebaseapp.com',
    storageBucket: 'learnstorm-63eb7.appspot.com',
    measurementId: 'G-8WG5J001TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRN2yZO4FLfHj8to5znM1j6GVqvlYvklM',
    appId: '1:742349350458:android:b09c2c9c3d763e92173703',
    messagingSenderId: '742349350458',
    projectId: 'learnstorm-63eb7',
    storageBucket: 'learnstorm-63eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXZepykIjfQUaEimGGXKL3p5nnjvp7kEY',
    appId: '1:742349350458:ios:663ab2e2abe81f17173703',
    messagingSenderId: '742349350458',
    projectId: 'learnstorm-63eb7',
    storageBucket: 'learnstorm-63eb7.appspot.com',
    iosBundleId: 'com.example.learnstorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXZepykIjfQUaEimGGXKL3p5nnjvp7kEY',
    appId: '1:742349350458:ios:663ab2e2abe81f17173703',
    messagingSenderId: '742349350458',
    projectId: 'learnstorm-63eb7',
    storageBucket: 'learnstorm-63eb7.appspot.com',
    iosBundleId: 'com.example.learnstorm',
  );
}
